api: https://api.github.com
repo: 
 - SEMICeu/Core-Person-Vocabulary
 - SEMICeu/Core-Location-Vocabulary
 - SEMICeu/Core-Business-Vocabulary
 - SEMICeu/CPOV
 - SEMICeu/CCCEV
 - SEMICeu/Core-Public-Event-Vocabulary
 - SEMICeu/CPSV
 - SEMICeu/CPSV-AP
 - SEMICeu/SDG-search-service-model
 - SEMICeu/ADMS-AP
 - SEMICeu/DCAT-AP
 - SEMICeu/StatDCAT-AP
 - SEMICeu/GeoDCAT-AP
issuesperpage: 20
issuesstate: all
issuessortby : created
waitingtime: 1
<<<<<<< HEAD
token: ###REPLACE###
=======
token: ACCESS_TOKEN
>>>>>>> 7f70f47007b5f51c9e37a26a120891a48c6411ff
mediatype: application/vnd.github.v3+jso
output: output.csv
header:
 - 'Repo name'
 - 'created'
 - '#issues'
 - '#issues open'
 - '#issues closed'
 - '#comments'
 - '#users'
 - "locations"
delimiter: ;
encoding: utf-8
totallabel: TOTAL
bars:
  repos:
    description: Repos
    colour: MAGENTA
    leave: True
  pages:
    description: Pages of issues
    colour: RED
    leave: False
  issues:
    description: Issues
    colour: YELLOW
    leave: False
  comments:
    description: Comments
    colour: GREEN
    leave: False 
