api: https://api.github.com
repo: 
 - SEMICeu/Core-Business-Vocabulary
 - SEMICeu/Core-Location-Vocabulary
 - SEMICeu/Core-Person-Vocabulary
 - SEMICeu/CPOV
 - SEMICeu/Core-Public-Event-Vocabulary
 - SEMICeu/CCCEV
 - SEMICeu/CPSV-AP
 - SEMICeu/DCAT-AP
 - SEMICeu/CAMSS_CSSV
issuesperpage: 20
issuesstate: all
issuessortby : created
waitingtime: 1
token: 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
mediatype: application/vnd.github.v3+jso
output: output.csv
header:
 - 'Repo name'
 - 'created'
 - '#issues'
 - '#issues open'
 - '#issues closed'
 - '#comments'
 - '#users'
 - "locations"
delimiter: ;
encoding: utf-8
totallabel: TOTAL
bars:
  repos:
    description: Repos
    colour: MAGENTA
    leave: True
  pages:
    description: Pages of issues
    colour: RED
    leave: False
  issues:
    description: Issues
    colour: YELLOW
    leave: False
  comments:
    description: Comments
    colour: GREEN
    leave: False 